//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cod_policia.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class codigo_policiaEntities : DbContext
    {
        public codigo_policiaEntities()
            : base("name=codigo_policiaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<articulo> articulo { get; set; }
        public virtual DbSet<libro> libro { get; set; }
        public virtual DbSet<noticia> noticia { get; set; }
        public virtual DbSet<requisitos> requisitos { get; set; }
        public virtual DbSet<tipo_usuario> tipo_usuario { get; set; }
        public virtual DbSet<titulo> titulo { get; set; }
        public virtual DbSet<tramite> tramite { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
